CREATE DATABASE StuIn;


USE StuIn ;

CREATE TABLE STUDENTS(
    STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    ADDRESS VARCHAR(20),
    AGE INT,
    DOB DATE);
    
    
INSERT INTO STUDENTS VALUES(1,'DEV SHARMA','91 ABC STREET',25,'1991-08-19');
INSERT INTO STUDENTS VALUES(2,'ARYA RAJPUT','77 XYZ STREET',21,'1999-09-29');
INSERT INTO STUDENTS VALUES(3,'GAURAV VERMA','101 YEMEN ROAD',29,'2000-01-01');

SELECT * FROM STUDENTS;

 CREATE INDEX idx
 ON STUDENTS(NAME);
 
 SELECT *
 FROM STUDENTS USE INDEX(idx);
 
 
 
 DESC STUDENT;
 
 ALTER TABLE STUDENT DROP INDEX idx;
 
 
 
 
 CREATE TABLE EMPLOYEE(
   EMP_ID INT,
   EMP_NAME VARCHAR(20),
   AGE INT,
   DOB DATE,
   SALARY DECIMAL(7.2)); 
   
 CREATE INDEX EMP
 ON EMPLOYEE(EMP_ID,EMP_NAME); 
 
ALTER TABLE EMPLOYEE
DROP INDEX EMP;

